---
####### All play ############
- name: Remove the lab related packages and directories 
  become: yes
  hosts: head
  tasks:
    - name: stop services
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      with_items:
        - mariadb 
        - nfs-server

    - name: uninstall pkgs 
      ansible.builtin.dnf:
        name:  "{{ item }}"
        state: absent
      with_items:
        - ansible
        - rpm-build
        - pam-devel
        - perl
        - perl-DBI
        - openssl-devel
        - readline-devel
        - mariadb-devel
        - mariadb-server
        - python3-PyMySQL
        - munge-devel
        - munge
        - munge-libs
        - "mariadb-*"
        - epel-release 

    - name: remove files
      ansible.builtin.file:
        name: "{{ item }}"
        state: absent
      with_items:
        - /etc/exports
        - /var/lib/mysql

